name: pfnet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - numpy
  - matplotlib
  - tensorflow
  - tensorflow-gpu
  - keras
  - opencv=4.1
  - cudnn=7.6.0=cuda10.0_0
  - scikit-image
  - pil
  - pycocotools
#  - pip:
#      - skimage
